# Generated by Django 5.1.6 on 2025-02-17 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_apply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Apply',
        ),
    ]
